dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)

install.packages("devtools", dependencies=TRUE)
install.packages("progress", dependencies=TRUE)
install.packages("conflicted", dependencies=TRUE)
install.packages("cowplot", dependencies=TRUE)
install.packages("dplyr", dependencies=TRUE)
install.packages("dtw", dependencies=TRUE)
install.packages("formattable", dependencies=TRUE)
install.packages("ggplot2", dependencies=TRUE)
devtools::install_github("teunbrand/ggh4x")
install.packages("network", dependencies=TRUE)
install.packages("sna", dependencies=TRUE)
install.packages("ggnetwork", dependencies=TRUE)
install.packages("ggrepel", dependencies=TRUE)
install.packages("gridExtra", dependencies=TRUE)
install.packages("igraph", dependencies=TRUE)
install.packages("kableExtra", dependencies=TRUE)
install.packages("matrixStats", dependencies=TRUE)
install.packages("patchwork", dependencies=TRUE)
install.packages("qgraph", dependencies=TRUE)
install.packages("scales", dependencies=TRUE)
install.packages("tidyverse", dependencies=TRUE)
install.packages("TSclust", dependencies=TRUE)
install.packages("this.path", dependencies=TRUE)
install.packages("tikzDevice", dependencies=TRUE)
